# Generated by Django 3.0.6 on 2020-07-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
