# Generated by Django 3.0.2 on 2020-02-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_proinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proinfo',
            old_name='name',
            new_name='title',
        ),
    ]
