# Generated by Django 3.0.2 on 2020-03-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200224_0048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='proInfo',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',)},
        ),
    ]
