# Generated by Django 3.0.6 on 2020-07-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200313_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
